name: Zpracování SAP.xlsx

on:
  workflow_dispatch:

jobs:
  process-excel:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repozitáře
        uses: actions/checkout@v3

      - name: Nastavení Pythonu
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalace závislostí
        run: |
          pip install -r requirements.txt

      - name: Spuštění skriptu
        run: |
          python sap_processor.py

      - name: Nahrání výsledků (Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: SAP-outputs
          path: sklady_porovnani/output/SAP.xlsx
          if-no-files-found: warn